::PLUGIN: "OfflineHelp" par Anton75012
::DESC: "Plugin pour avoir l'aide en offline."
::COPYRIGHT: (c) Anton75012, svp ne pas reproduire.
::FICHIER: help.bat
@echo off
if not exist PluginsData\OfflineHelp mkdir PluginsData\OfflineHelp
if exist PluginsData\OfflineHelp\help.hta del PluginsData\OfflineHelp\help.hta
echo "<head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta name="description" content="Minilogiciel hCmd"><link rel="shortcut icon" href="http://hugoland.olympe.in/hCmd/help/features/fr/hcmd.ico" type="image/x-icon"> <link rel="icon" href="http://hugoland.olympe.in/hCmd/help/features/fr/hcmd.ico" type="image/x-icon"><title>-- hCmd -- (c) Hugo-Minilogiciels</title></head><body style="background:#cccccc;"><font face="impact"><center><h1>hCmd - Aide sur les commandes.</h1>Tapez des commandes, ajoutez des plugins!<br></center>Voici une liste de commandes utilisables sans plugins!</font><p><font face="impact"></font></p><table><tbody><tr><th>Commande</th><th>&nbsp;</th><th>Description</th></tr><tr><td>/?</td><td>&nbsp;</td><td>Vous montre cette page.</td></tr><tr><td>/cc</td><td>&nbsp;</td><td>Changer la couleur temporairement.</td></tr><td>/r</td><td>&nbsp;</td><td>Naviguer dans les dossiers &amp; sous dossiers, et les renommer.</td></tr>    <td>/stop</td><td>&nbsp;</td><td>Fermer proprement l'invite.</td></tr><td>/cmd</td><td>&nbsp;</td><td>Ouvrir les commandes Windows. (MS-DOS)</td></tr><td>/dirg</td><td>&nbsp;</td><td>Outil de gestion des dossiers.</td></tr><td>/frdos</td><td>&nbsp;</td><td>Accéder à la console de MS-DOS en français!</td></tr><td>/bb</td><td>&nbsp;</td><td>Installer Batbox.exe dans un dossier choisi.</td></tr><td>/!</td><td>&nbsp;</td><td>Conseil aléatoire.</td></tr><td>/ping</td><td>&nbsp;</td><td>Réaliser le ping d'une ip/d'un site.</td></tr><td>/clear</td><td>&nbsp;</td><td>Vider les fichiers temporaires d'hCmd (C:\temp\hCmd\)</td></tr><td>/deltemp</td><td>&nbsp;</td><td>Utilitaire de suppression de fichiers (corbeille/fichiers temporaires/etc)</td></tr><td>/calc</td><td>&nbsp;</td><td>Calculette.</td></tr><td>/heure</td><td>&nbsp;</td><td>Donne la date et l'heure.</td></tr><td>/heure2</td><td>&nbsp;</td><td>Heure actualisée en temps réel.</td></tr><td>/config IA false</td><td>&nbsp;</td><td>Désactiver la voix.</td></tr><td>/config IA true</td><td>&nbsp;</td><td>Activer la voix.</td></tr><td>/fic</td><td>&nbsp;</td><td>Edition de fichiers.</td></tr><td>/rl</td><td>&nbsp;</td><td>Reload du logiciel, afin d'appliquer les modifications de /config.</td></tr><td>/config</td><td>&nbsp;</td><td>Utilisation: '/config paramètre valeur' <a href="http://hugoland.olympe.in/hCmd/help/features/fr/config">Plus d'infos</a> (Requiert une connexion internet).</td></tr><td>/reset</td><td>&nbsp;</td><td>Purger le dossier hCmd, remettre à 0 les configs. (plugins gardés)</td></tr><td><b>Script original par Hugo7</b></td></tr></tbody></table></font></body></html>" >>PluginsData\OfflineHelp\help.hta
start PluginsData\OfflineHelp\help.hta
del session.lock
call hCmd.bat